### ISSUE TITLE
BeanWrapperRowMapper throws BinderException on trying to read basic String files.

### ISSUE THREAD

**Issue by prateekchachra** [spring-projects/spring-batch-extensions#32]
From a DataBinder binder, say I were to register a custom editor by calling: 

binder.registerCustomEditor(String.class, new StringTrimmerEditor(true))

It tried to read this particular row as a Long; hence an IllegalArgumentException leading to the aforementioned BinderException.

**Comment by waasikhaan** [comment]
@prateekchachra Could you please add more details here? I am not sure but do check the value that you are getting from the file. Excel store values in floating point, may be that was the issue here as well. I ran into an issue where i am reading a value in Integer but the POI return me 1 as 1.0 and i am getting the binder exception or something like that. For that i used the Dataformatter by changing the POISHEET class to fix that.

**Comment by mdeinum** [comment]
Close due to inactivity, no response from the author of this issue.
