### ISSUE TITLE
Is project abandoned?

### ISSUE THREAD

**Issue by pakmans** [spring-projects/spring-batch-extensions#46]
Is this project dead?  
I see a lot of useful pull requests that have been ignored for several years.
How can we push this forward?

**Comment by anthonyrichir** [comment]
It's indeed a huge disappointment to see this project in a dead end, I would like to help as much as I can as well.

**Comment by mdeinum** [comment]
I'm the original owner of this project and the main issue is that I don't have commit rights to this repository. So even if I wanted to incorporate the changes made here I cannot.

I merged all the latest changes into the "previous" location of the [Spring Batch Excel](https://github.com/mdeinum/spring-batch-excel) project. So it should now be up to date with the status as in this project. 

 I also upgraded the Spring Batch, Apache POI and several other dependencies to newer versions as well, as upgraded to minimal Java version to 1.8 (to match the Spring Batch 4.0 one). 

If there are pull requests that people want to see merged, I suggest redoing them to the aforementioned location. I'll also try to get out an officially released version to a maven repository somewhere.

**Comment by pakmans** [comment]
Excelent, and thank your time and effort! This is a nice little project that should be more generally known/used.

**Comment by mdeinum** [comment]
I hoped that would happen with moving it to this extensions project, however that didn't really work out.

**Comment by mminella** [comment]
We are having internal conversations right now as to how to best manage this going forward.  We do want to keep it around so stay tuned.

**Comment by nstdio** [comment]
@mminella Any updates on this?

**Comment by benas** [comment]
We are planning to start releasing community driven modules to Maven Central. However, we are not intending to merge PRs for new modules that won't be maintained by a community lead, that's why we are looking for a lead for each module. @mdeinum has accepted to take the lead on `spring-batch-excel` and will drive the evolution of that module from now on.

A module lead will be responsible for all issues/PRs related to the module (s)he leads, and the Spring Batch team will take care of the releases to Maven Central on demand. So if someone is interested in taking the lead on an existing module or a new module, please reach out to me or @mminella and we will take it from there. We look forward to the many modules that could be contributed to this repository!

A blog post will follow on [spring.io](https://spring.io/blog) with a tweet from [@springbatch](https://twitter.com/springbatch), so stay tuned!
