### ISSUE TITLE
Date format when reading

### ISSUE THREAD

**Issue by pivsxii** [spring-projects/spring-batch-extensions#88]
In my file dates are in DD/MM/YYYY and when Spring/POI are reading data org.apache.poi.ss.usermodel.DataFormatter is used and in performDateFormatting method the parameter dateFormat has a pattern of M/d/yy.

Is there a way to force the date pattern when reading ?

My RowMapper configuration is 

```
	<bean id="caricaAnagraficheReader" class="org.springframework.batch.extensions.excel.poi.PoiItemReader" scope="step">
		<property name="resource" value="file:#{batchParameters.genericBatchParameters.allegatoNomeCompleto}" />
		<property name="linesToSkip" value="1" />
	    <property name="rowMapper">
	        <bean class="it.blue.batch.portali.components.CaricaAnagraficheRowMapper" />
    	</property>
	</bean>
```

**Comment by mdeinum** [comment]
This is a question, which is better asked on StackOverflow. Which in fact you [already did](https://stackoverflow.com/questions/70937915/date-format-in-spring-batch-excel) and for which I provided the answer (well actually a comment). 

> It will use the date-format from the cell if it is available (if no format it set and only type date it will fallback to the default JDK locale for formatting). You could try to explicitly set the format for the date-cells in your excel sheet. Everything currently is delegated to Apache POI ...

**Comment by pivsxii** [comment]
Hi, i posted in both sites to be sure to get as much response as I can, and to propose (as you already did) to add and additional option for Rowmapper to use a non default Locale when reading the file.

**Comment by mdeinum** [comment]
The `RowMapper` isn't reading the file, the `PoiItemReader` is doing that. The `RowMapper` is for mapping the resulting `String[]` to your own objects. One thing you could try is to create a `JobExecutionListener` which, at the start of the job, does a `LocaleUtil.setUserLocale(<Your-Locale.Here>)` and after the execution does `LocaleUtil.resetUserLocale();`. See if that helps. 

The `DataFormatter` doesn't really allow for a different format to be set for reading, it is either the one used in the Excel document (when set) else it will create some based on the users locale and the default pattern of `"EEE MMM dd HH:mm:ss zzz yyyy"`. 

Without changing the API I don't think there is much we can do on the reading side, although I have been considering aligning it more with the JDBC counterpart and adding  `getDate` and `getInteger` etc. instead of using a `String[]` for the row representation. Drawback of this is that the streaming approach will still only work with `String` and not types, due to how the streaming is implemented in Apache POI (and probably due to how that works in OOXML in the first place). That difference would mean a divergence in handling for the classic case and the streaming case. 

Another approach we could investigate is to subclass the `DataFormatter` and always return an ISO formatted DATETIME, so the result is at least reliable and can be tweaked in a a `RowMapper` (you could parrse the ISO DATE TIME to anything you want if you always know the input format). But looking at it, it isn't really designed to be extended and the methods we would need to extend are mostly marked `private`. So that would be a different challenge.
