### ISSUE TITLE
When extracting data from the RowSet (rs) year in date cell is shortened

### ISSUE THREAD

**Issue by alimulondo** [spring-projects/spring-batch-extensions#98]
sample code:
```
var result = rs.getCurrentRow();
var actualDate = result[5]; // returns "5/29/19" year has been shorted from "2019" to "19"
var expected = "5/29/2019";
assertEquals(expected, actualDate);
```

**Comment by mdeinum** [comment]
Could you please specify which filetype you are using? `xls` or `xlsx`? Or even better provide a sample (failing test case with an data file). 

The point is that the library uses whatever ApachePOI seems fit to return and it actually returns the internal representation used by Excel, not the formatted date.

**Comment by alimulondo** [comment]
Hi Marten,
It is `xlsx` format!
It's a real production app I may not be able to provide sample code. 
However I understand the limitation you just stated. Can I force it to just read the cell as string and not convert it to date, I then convert that string to date format of my choice. 
It return string array so I wonder why it labors to convert a given cell to date. 
Thanks

**Comment by alimulondo** [comment]
Let me provide some sample data and code in a short while.

**Comment by alimulondo** [comment]
Here is the link to the demo : [demo](https://github.com/alimulondo/spring-batch-data-demo)

**Comment by alimulondo** [comment]
It contains both the file and the working demo. 
Thanks.

**Comment by mdeinum** [comment]
FIrst of all thanks for the files and code. That is a starting point for me. Could you tell me one more thing, which `Locale` are you using in Excel? I wonder if it would make sense to set it for parsing the files (currently it will use the system default). 

Looking at the javadoc from `DataFormatter` this might be more involved then I thought. 

> Some formats are automatically "localized" by Excel, eg show as mm/dd/yyyy when loaded in Excel in some Locales but as dd/mm/yyyy in others. **These are always returned in the "default" (US) format, as stored in the file**. Some format strings request an alternate locale, eg [$-809]d/m/yy h:mm AM/PM which explicitly requests UK locale. These locale directives are (currently) ignored. You can use [DateFormatConverter](https://poi.apache.org/apidocs/3.17/org/apache/poi/ss/util/DateFormatConverter.html) to do some of this localisation if you need it.

Note the empasized text (mine). Apparently everything will use the format as defined, unless it is a date/time field it will use the US locale by default (which is basically how it is stored internally). 

I need some time to ponder this on how to best solve this, my first gut feeling is to always convert date/time to ISO formatted values instead of what is in the file. That way it is at least consistent. Or to configure a `Locale` and use the default date/time formatting for that (but that could lead to surprises when not explicitly setting it and using a system default).

**Comment by alimulondo** [comment]
Did you get the updated sample data? There are two columns in the sheet. First column contains date in **Ugandan locale**  which when extracted picks only the last digits of the year. The second column contains date in **Armenian locale** which when extracted from the sheet picks all the digits of the year as expected. 
So the point am trying to make is that some locales result to the right extracted data and others don't.

**Comment by alimulondo** [comment]
So can you give us the flexibility to set locale type we expect it to before extraction. 
Am assuming it is using some default.

**Comment by mdeinum** [comment]
Well there are 2 things to consider. 1 is what is in the XLSX and the other is what Apache POI uses. But we can configure the `DataFormatter` with a `Locale` to use for formatting, so that is a possibility. I could also port that to be useful for both XLS and XLSX. 

I'll have a go see what I can do, including updating the XLSX to allow for ISO date formatting.

**Comment by alimulondo** [comment]
Thanks a lot! Let me check it out.

**Comment by alimulondo** [comment]
Where these changes omitted in the current version :  `<dependency>
    <groupId>org.springframework.batch</groupId>
    <artifactId>spring-batch-core</artifactId>
    <version>5.0.1</version>
</dependency>`

**Comment by mdeinum** [comment]
These changes aren't part of Spring Batch but rather this specific Spring Batch extension. I haven't yet released a version as I was actually awaiting your confirmation. There currently isn't (yet) a version that has been tested against Spring Batch 5.x (that would probably become 0.2). Although I did some testing and the project appears to work just fine (but that was against a milestone release).

**Comment by mdeinum** [comment]
You can checkout the code and build the artifact yourself.

**Comment by alimulondo** [comment]
Sounds good. Let me do that.
